FIND_PATH(CPP_REST_INCLUDE_DIR http_client.h
    /usr/include/cpprest
    "${CMAKE_SOURCE_DIR}/include"
    "${CMAKE_SOURCE_DIR}/include/cpprest"
    NO_DEFAULT_PATH
)

SET(CMAKE_FIND_LIBRARY_PREFIXES "" "lib")
SET(CMAKE_FIND_LIBRARY_SUFFIXES ".so" ".a" ".lib")
FIND_LIBRARY(CPP_REST_LIBRARY NAMES cpprest PATHS
    /usr/lib/x86_64-linux-gnu
    /usr/lib
    "${CMAKE_SOURCE_DIR}/lib"
    NO_DEFAULT_PATH
)

IF (CPP_REST_INCLUDE_DIR AND CPP_REST_LIBRARY)
    SET(CPP_REST_FOUND TRUE)
ENDIF (CPP_REST_INCLUDE_DIR AND CPP_REST_LIBRARY)

IF (CPP_REST_FOUND)
   IF (NOT CPP_REST_FIND_QUIETLY)
       MESSAGE(STATUS "Found C++ REST: ${CPP_REST_LIBRARY}")
   ENDIF (NOT CPP_REST_FIND_QUIETLY)
ELSE (CPP_REST_FOUND)
    IF (CPP_REST_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find C++ REST")
    ENDIF (CPP_REST_FIND_REQUIRED)
ENDIF (CPP_REST_FOUND)
